name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set Up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Up Python Runtime
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Latest Python Compiling Tools
        run: |
          pip install --upgrade pip
          # Forcing the server to get the latest version removes old tool errors
          pip install --upgrade flet yt-dlp

      - name: Pre-Install Native Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Initialize Android SDK Manager
        uses: android-actions/setup-android@v3

      - name: Build Standalone Android Package
        run: |
          # Links compiler paths directly inside the global machine environment variables
          flutter config --android-sdk "$ANDROID_HOME"
          yes | sdkmanager --licenses || true
          
          # Clean execution command that grabs project configurations automatically out of flet.yaml
          flet build apk

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drac-media-App
          path: build/apk/*.apk
